-- 创建表aa，bb表
DROP table if EXISTS aa; create table aa(a int(1)) ENGINE=Innodb; DROP table if EXISTS bb; create table bb(b int(1))ENGINE=Innodb;
-- 总过程
DROP PROCEDURE IF EXISTS A1;
CREATE PROCEDURE A1()
TOP:BEGIN

	SET @BASE_ERROR = 0;
	START TRANSACTION;
		IF @BASE_ERROR = 1 THEN 
				LEAVE TOP;
			ELSE 
				CALL B1();
			END IF; 
		IF @BASE_ERROR = 1 THEN 
				LEAVE TOP;
			ELSE 
				CALL C1();
			END IF; 

	SELECT @BASE_ERROR;

        IF @BASE_ERROR = 1 THEN 
			ROLLBACK;
        ELSE
            COMMIT;
        END IF;

END;

-- 子过程B
DROP PROCEDURE IF EXISTS B1;
CREATE PROCEDURE B1()
BEGIN
	DECLARE P_ERROR INTEGER DEFAULT 0; 
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN SHOW ERRORS;  SET P_ERROR = 1; END;
		INSERT INTO AA VALUES(44444444444444444443); -- 出错
		SET @BASE_ERROR = P_ERROR;
END;

-- 子过程C
DROP PROCEDURE IF EXISTS C1;
CREATE PROCEDURE C1()
BEGIN
	DECLARE P_ERROR INTEGER DEFAULT 0; 
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN SHOW ERRORS; SET P_ERROR = 1; END;
		INSERT INTO BB VALUES(2);
		SET @BASE_ERROR = P_ERROR;
END;

CALL A1();
SELECT * FROM AA;
SELECT * FROM BB;
DELETE FROM AA; DELETE FROM BB; 